name: Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: chmod +x Build_Env.sh && ./Build_Env.sh
    - name: run cppcheck
      run: cppcheck 3_Implementation
 
